### PR TITLE
Update Ubuntu Requirement

### PR DESCRIPTION
**Pull request by Snowiiii**
Forgot to do this in https://github.com/ppp-project/ppp-ci/pull/2

### CODE REVIEW

**Comment by RICCIARDI-Adrien** [comment]
No worries, the readme will be reworked as soon as Buildroot 2024.02 is released. The `pppd` package will then be updated to version 2.5.0 and this will allow some improvements.

**Comment by Snowiiii** [comment]
Fine, Btw the workflows in ppp are outdated too, And i did not really understand that ubuntu version you prefer in `buildroot` its still `20.04` in solaris its `22.04` and in ubuntu its `latest`. I generally prefer latest

**Comment by RICCIARDI-Adrien** [comment]
Indeed, quite all is outdated.
When Buildroot 2024.02 is released, I can update everything like I did for the radvd CI : https://github.com/radvd-project/radvd-ci.

I previously had some issues when the Ubuntu latest image was updated to a newer version, that's why I usually specify a precise version. However, here this should be fine to use `ubuntu-latest`, as Buildroot build system is nicely stable nowadays.

**Comment by Snowiiii** [comment]
okay

**Pull request closed without merging**
